### ISSUE TITLE
Plugin does not work when running from Fiji installation

### ISSUE THREAD

**Issue by hadim** [hadim/Fiji_MaskRCNN#3]
```
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:577)
	at org.scijava.util.ClassUtils.getAnnotatedFields(ClassUtils.java:196)
	at org.scijava.util.ClassUtils.getAnnotatedFields(ClassUtils.java:166)
	at org.scijava.Context.getParameterFields(Context.java:447)
	at org.scijava.Context.inject(Context.java:384)
	at org.scijava.Context.inject(Context.java:501)
	at org.scijava.Context.inject(Context.java:386)
	at org.scijava.module.DefaultModuleService.createModule(DefaultModuleService.java:171)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:209)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:200)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:185)
	at org.scijava.command.DefaultCommandService.run(DefaultCommandService.java:186)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:292)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:163)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
```

No idea what's happening.

**Comment by hadim** [comment]
It seems to be an IJ components version issue. I am not gonna worry about it for now and wait for Scijava be updated to Fiji.
